### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/surf-ice#1]
I tried compiling your software on my system, and it fails with [this log](http://bpaste.net/show/1203a4df6f19).

Basically what my system did here, is simply cd to the project root and run:

``` 
lazbuild -B --lazarusdir="/usr/share/lazarus/" surfice.lpi
```

Perhaps I am trying to compile the wrong project file?

**Comment by neurolabusc** [comment]
OK, the issue here is that FreePascal's glext has not yet been updated to support OpenGL Core or the legacy OpenGL geometry engines...
  http://mantis.freepascal.org/view.php?id=29051
So until the next version of freepascal, we need to use the updated version of glext.pp included in my distribution instead of the default one that comes with fpc.

I am able to successfully build SurfIce using 

`lazbuild -B surface.lpr`

using Lazarus 1.6.2 both on NeuroDebian 8 and CentOS 6.6. The trick is that the .lpi file contains a conditional to override the glext:

`if TargetOS='linux' then
  UnitPath += ';/usr/share/fpcsrc/3.0.0/packages/opengl/src';`

On both of these distributions, the original glext.pp file we need to override is located in /usr/share/fpcsrc/3.0.0/packages/opengl/src - does this file have the same location with Gentoo?

**Comment by TheChymera** [comment]
The Gentoo location is `/usr/lib/fpc/3.0.0/source/packages/opengl/src/glext.pp`.

**Comment by neurolabusc** [comment]
That would explain it. Can you see if you can compile the updated source.

**Comment by TheChymera** [comment]
Thank you, it compiles nicely now.
