### ISSUE TITLE
Problem loading GIFTI surface

### ISSUE THREAD

**Issue by pauldmccarthy** [neurolabusc/surf-ice#19]
Hi Chris,

Surf-Ice seems to be having some trouble with a particular type of GIFTI surface ([left_subthalamic_nucleus.gii.txt](https://github.com/neurolabusc/surf-ice/files/4793374/left_subthalamic_nucleus.gii.txt) - added `.txt` so github would accept it):

![left_subthalamic_nucleus](https://user-images.githubusercontent.com/236128/84913944-f63bc180-b0b2-11ea-812c-90538e89ebc0.png)

The triangle winding order is clockwise, although I don't thiink this is the cause of the problem. 

The vertices and triangles in this file are encoded in plain text, rather than the more common base64, e.g.:

```
<Data> -6.549202 -11.776001  -9.900600
 -6.357399 -12.049004  -9.717800
...
-12.818001 -12.528999  -4.303101
-12.728996 -12.144997  -4.247803</Data>
...
<Data>0 1 2
0 3 4
...
575 581 578
576 578 581</Data>
```

I believe that this is valid according to the GIFTI specification (although the spec is under-specified with regards to plain-text encoding).

I experimented a little, adding extra line breaks into the GIFTI file ([left_subthalamic_nucleus_edit.gii.txt](https://github.com/neurolabusc/surf-ice/files/4793373/left_subthalamic_nucleus_edit.gii.txt)):

```
<Data>
 -6.549202 -11.776001  -9.900600
...
-12.728996 -12.144997  -4.247803
</Data>
...
<Data>
0 1 2
...
576 578 581
</Data>
```

and this seems to fix the rendering:

![left_subthalamic_nucleus_edit](https://user-images.githubusercontent.com/236128/84914813-fa1c1380-b0b3-11ea-8dda-45ed0d3ff87c.png)

So my guess is that the GIFTI parsing logic in Surf-Ice is ignoring text which appears on the same line as an opening/closing XML element?

**Comment by neurolabusc** [comment]
@pauldmccarthy thanks for sample and diagnosis - this will be fixed in the next release. If you want a beta build tell me if you prefer MacOS, Linux or Windows. If you created this file, I would implore you to [use any other format](https://neurostars.org/t/displaying-surface-files-generated-by-neurovault/6693/6) if you value precision, speed or file size.

As an aside, the [GIfTI format](https://www.nitrc.org/projects/gifti/) explicitly specifies that for NIFTI_INTENT_TRIANGLE that `the three nodes are listed in counter- clockwise winding (right-hand rule)`. Likewise, for  [OpenGL the default front face is CCW](https://www.khronos.org/opengl/wiki/Face_Culling). The Advanced/ReverseFaces menu item will reverse the winding order. Alternatively, some shaders like Phong have an option "LightBackFaces" that will provide two-sided lighting. By default, the shaders (with the exception of `MatCap2Side`) will tend to show back-faces as de-saturated and matte relative to front faces.

**Comment by pauldmccarthy** [comment]
Thanks @neurolabusc! These meshes are part of [MIST](https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/MIST), a sub-cortical segmentation tool bundled with FSL, so unfortunately I don't have any control over the choice of format (nor its violations of the GIFTI spec). I had missed the requirement of counter-clockwise winding order in the GIFTI spec though.

**Comment by neurolabusc** [comment]
Fixed in pre-release and future releases.
