### ISSUE TITLE
bilateral mesh loading when hemisphere is chosen

### ISSUE THREAD

**Issue by dkp** [neurolabusc/surf-ice#24]
Hi Chris,

From browsing your GitHub site, it looks like you may have seen this problem before:
A bilateral mesh loading when a hemisphere should be loading instead:

/Applications/Surfice/BrainNet/BrainMesh_ICBM152.lh.mz3
/Applications/Surfice/BrainNet/BrainMesh_ICBM152.mz3
/Applications/Surfice/BrainNet/BrainMesh_ICBM152.rh.mz3

Mac OSX Mojave 10.14.6
Surf Ice v1.0.20201102 64-bit x86-64 Cocoa LLVM

Interestingly, if I copy the hemisphere files to a different name and file folder, then they load correctly, at least for a while.
I am double-clicking the files to load them...but dragging the files onto surfice seems to result in the same problem.
Sorry, I don't know what to make of this. It is almost as if the surfice environment is changing depending on the sequence of files loaded beforehand??  

Thanks for your time...I like the tool very much.

-Dianne

**Comment by neurolabusc** [comment]
Open the "Preferences" window and uncheck the "Load bilateral meshes" check box if you want only the selected file to be opened. You can also turn bilateral loads on (1) or off (0) with the `meshloadbilateral` scripting function, as illustrated in the script below. There is a caveat for macOS users: due to sandboxing, applications are not able to load files unless the user explicitly selects them (through a dialog or a drag-and-drop). Therefore, if you want to load bilateral meshes, drag and drop BOTH the lh and rh image.

```
import gl
gl.resetdefaults()
gl.meshloadbilateral(1)
gl.azimuthelevation(70, 15)
gl.meshload('BrainMesh_ICBM152.rh.mz3')
gl.overlayload('motor_4t95vol.nii.gz')
gl.overlayminmax(1,2,12)
gl.overlayload('motor_4t95vol.nii.gz')
gl.overlayminmax(2,-1,-2)
gl.colorbarvisible(1)
gl.overlaytransparencyonbackground(25)
gl.meshcurv()
gl.shadername('MatCap');
gl.shadermatcap('Cortex3')
gl.hemispheredistance(0.62)
gl.hemispherepry(-35)
gl.azimuthelevation(180,0)
```

**Comment by dkp** [comment]
Thanks so much!
Very cool!

-Dianne

Dianne Patterson, Ph.D
Speech, Language and Hearing Sciences, Room 314
dkp@arizona.edu
________________________________
